# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='mpf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cserver.proto\x12\x03mpf\"3\n\x0fSlideAddRequest\x12\x12\n\nslide_name\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x12\n\x10SlideAddResponse2J\n\x0fMediaController\x12\x37\n\x08\x41\x64\x64Slide\x12\x14.mpf.SlideAddRequest\x1a\x15.mpf.SlideAddResponseb\x06proto3'
)




_SLIDEADDREQUEST = _descriptor.Descriptor(
  name='SlideAddRequest',
  full_name='mpf.SlideAddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='slide_name', full_name='mpf.SlideAddRequest.slide_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='mpf.SlideAddRequest.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=72,
)


_SLIDEADDRESPONSE = _descriptor.Descriptor(
  name='SlideAddResponse',
  full_name='mpf.SlideAddResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['SlideAddRequest'] = _SLIDEADDREQUEST
DESCRIPTOR.message_types_by_name['SlideAddResponse'] = _SLIDEADDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SlideAddRequest = _reflection.GeneratedProtocolMessageType('SlideAddRequest', (_message.Message,), {
  'DESCRIPTOR' : _SLIDEADDREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:mpf.SlideAddRequest)
  })
_sym_db.RegisterMessage(SlideAddRequest)

SlideAddResponse = _reflection.GeneratedProtocolMessageType('SlideAddResponse', (_message.Message,), {
  'DESCRIPTOR' : _SLIDEADDRESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:mpf.SlideAddResponse)
  })
_sym_db.RegisterMessage(SlideAddResponse)



_MEDIACONTROLLER = _descriptor.ServiceDescriptor(
  name='MediaController',
  full_name='mpf.MediaController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=94,
  serialized_end=168,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddSlide',
    full_name='mpf.MediaController.AddSlide',
    index=0,
    containing_service=None,
    input_type=_SLIDEADDREQUEST,
    output_type=_SLIDEADDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEDIACONTROLLER)

DESCRIPTOR.services_by_name['MediaController'] = _MEDIACONTROLLER

# @@protoc_insertion_point(module_scope)
