# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='mpf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cserver.proto\x12\x03mpf\"\x11\n\x0fSlideAddRequest\"$\n\x10SlideAddResponse\x12\x10\n\x08slide_id\x18\x01 \x01(\r\"@\n\x05\x43olor\x12\x0b\n\x03red\x18\x01 \x01(\x02\x12\r\n\x05green\x18\x02 \x01(\x02\x12\x0c\n\x04\x62lue\x18\x03 \x01(\x02\x12\r\n\x05\x61lpha\x18\x04 \x01(\x02\"\xab\x03\n\x10WidgetAddRequest\x12\x10\n\x08slide_id\x18\x01 \x01(\r\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\r\x12\x19\n\x05\x63olor\x18\x05 \x01(\x0b\x32\n.mpf.Color\x12\x37\n\x0btext_widget\x18\x06 \x01(\x0b\x32 .mpf.WidgetAddRequest.WidgetTextH\x00\x12\x41\n\x10rectangle_widget\x18\x07 \x01(\x0b\x32%.mpf.WidgetAddRequest.WidgetRectangleH\x00\x12\x39\n\x0cimage_widget\x18\x08 \x01(\x0b\x32!.mpf.WidgetAddRequest.WidgetImageH\x00\x1a\x1a\n\nWidgetText\x12\x0c\n\x04text\x18\x01 \x01(\t\x1a\x30\n\x0fWidgetRectangle\x12\r\n\x05width\x18\x01 \x01(\x01\x12\x0e\n\x06height\x18\x02 \x01(\x01\x1a:\n\x0bWidgetImage\x12\r\n\x05width\x18\x01 \x01(\x01\x12\x0e\n\x06height\x18\x02 \x01(\x01\x12\x0c\n\x04path\x18\x03 \x01(\tB\x08\n\x06widget\"\x13\n\x11WidgetAddResponse\"$\n\x10ShowSlideRequest\x12\x10\n\x08slide_id\x18\x01 \x01(\r\"\x13\n\x11ShowSlideResponse2\xca\x01\n\x0fMediaController\x12\x37\n\x08\x41\x64\x64Slide\x12\x14.mpf.SlideAddRequest\x1a\x15.mpf.SlideAddResponse\x12\x42\n\x11\x41\x64\x64WidgetsToSlide\x12\x15.mpf.WidgetAddRequest\x1a\x16.mpf.WidgetAddResponse\x12:\n\tShowSlide\x12\x15.mpf.ShowSlideRequest\x1a\x16.mpf.ShowSlideResponseb\x06proto3'
)




_SLIDEADDREQUEST = _descriptor.Descriptor(
  name='SlideAddRequest',
  full_name='mpf.SlideAddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=38,
)


_SLIDEADDRESPONSE = _descriptor.Descriptor(
  name='SlideAddResponse',
  full_name='mpf.SlideAddResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='slide_id', full_name='mpf.SlideAddResponse.slide_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=76,
)


_COLOR = _descriptor.Descriptor(
  name='Color',
  full_name='mpf.Color',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='red', full_name='mpf.Color.red', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='green', full_name='mpf.Color.green', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blue', full_name='mpf.Color.blue', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='mpf.Color.alpha', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=142,
)


_WIDGETADDREQUEST_WIDGETTEXT = _descriptor.Descriptor(
  name='WidgetText',
  full_name='mpf.WidgetAddRequest.WidgetText',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='mpf.WidgetAddRequest.WidgetText.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=452,
)

_WIDGETADDREQUEST_WIDGETRECTANGLE = _descriptor.Descriptor(
  name='WidgetRectangle',
  full_name='mpf.WidgetAddRequest.WidgetRectangle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='mpf.WidgetAddRequest.WidgetRectangle.width', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='mpf.WidgetAddRequest.WidgetRectangle.height', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=502,
)

_WIDGETADDREQUEST_WIDGETIMAGE = _descriptor.Descriptor(
  name='WidgetImage',
  full_name='mpf.WidgetAddRequest.WidgetImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='mpf.WidgetAddRequest.WidgetImage.width', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='mpf.WidgetAddRequest.WidgetImage.height', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path', full_name='mpf.WidgetAddRequest.WidgetImage.path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=504,
  serialized_end=562,
)

_WIDGETADDREQUEST = _descriptor.Descriptor(
  name='WidgetAddRequest',
  full_name='mpf.WidgetAddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='slide_id', full_name='mpf.WidgetAddRequest.slide_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='mpf.WidgetAddRequest.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='mpf.WidgetAddRequest.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='mpf.WidgetAddRequest.z', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='mpf.WidgetAddRequest.color', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text_widget', full_name='mpf.WidgetAddRequest.text_widget', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rectangle_widget', full_name='mpf.WidgetAddRequest.rectangle_widget', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_widget', full_name='mpf.WidgetAddRequest.image_widget', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_WIDGETADDREQUEST_WIDGETTEXT, _WIDGETADDREQUEST_WIDGETRECTANGLE, _WIDGETADDREQUEST_WIDGETIMAGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='widget', full_name='mpf.WidgetAddRequest.widget',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=145,
  serialized_end=572,
)


_WIDGETADDRESPONSE = _descriptor.Descriptor(
  name='WidgetAddResponse',
  full_name='mpf.WidgetAddResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=574,
  serialized_end=593,
)


_SHOWSLIDEREQUEST = _descriptor.Descriptor(
  name='ShowSlideRequest',
  full_name='mpf.ShowSlideRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='slide_id', full_name='mpf.ShowSlideRequest.slide_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=631,
)


_SHOWSLIDERESPONSE = _descriptor.Descriptor(
  name='ShowSlideResponse',
  full_name='mpf.ShowSlideResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=633,
  serialized_end=652,
)

_WIDGETADDREQUEST_WIDGETTEXT.containing_type = _WIDGETADDREQUEST
_WIDGETADDREQUEST_WIDGETRECTANGLE.containing_type = _WIDGETADDREQUEST
_WIDGETADDREQUEST_WIDGETIMAGE.containing_type = _WIDGETADDREQUEST
_WIDGETADDREQUEST.fields_by_name['color'].message_type = _COLOR
_WIDGETADDREQUEST.fields_by_name['text_widget'].message_type = _WIDGETADDREQUEST_WIDGETTEXT
_WIDGETADDREQUEST.fields_by_name['rectangle_widget'].message_type = _WIDGETADDREQUEST_WIDGETRECTANGLE
_WIDGETADDREQUEST.fields_by_name['image_widget'].message_type = _WIDGETADDREQUEST_WIDGETIMAGE
_WIDGETADDREQUEST.oneofs_by_name['widget'].fields.append(
  _WIDGETADDREQUEST.fields_by_name['text_widget'])
_WIDGETADDREQUEST.fields_by_name['text_widget'].containing_oneof = _WIDGETADDREQUEST.oneofs_by_name['widget']
_WIDGETADDREQUEST.oneofs_by_name['widget'].fields.append(
  _WIDGETADDREQUEST.fields_by_name['rectangle_widget'])
_WIDGETADDREQUEST.fields_by_name['rectangle_widget'].containing_oneof = _WIDGETADDREQUEST.oneofs_by_name['widget']
_WIDGETADDREQUEST.oneofs_by_name['widget'].fields.append(
  _WIDGETADDREQUEST.fields_by_name['image_widget'])
_WIDGETADDREQUEST.fields_by_name['image_widget'].containing_oneof = _WIDGETADDREQUEST.oneofs_by_name['widget']
DESCRIPTOR.message_types_by_name['SlideAddRequest'] = _SLIDEADDREQUEST
DESCRIPTOR.message_types_by_name['SlideAddResponse'] = _SLIDEADDRESPONSE
DESCRIPTOR.message_types_by_name['Color'] = _COLOR
DESCRIPTOR.message_types_by_name['WidgetAddRequest'] = _WIDGETADDREQUEST
DESCRIPTOR.message_types_by_name['WidgetAddResponse'] = _WIDGETADDRESPONSE
DESCRIPTOR.message_types_by_name['ShowSlideRequest'] = _SHOWSLIDEREQUEST
DESCRIPTOR.message_types_by_name['ShowSlideResponse'] = _SHOWSLIDERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SlideAddRequest = _reflection.GeneratedProtocolMessageType('SlideAddRequest', (_message.Message,), {
  'DESCRIPTOR' : _SLIDEADDREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:mpf.SlideAddRequest)
  })
_sym_db.RegisterMessage(SlideAddRequest)

SlideAddResponse = _reflection.GeneratedProtocolMessageType('SlideAddResponse', (_message.Message,), {
  'DESCRIPTOR' : _SLIDEADDRESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:mpf.SlideAddResponse)
  })
_sym_db.RegisterMessage(SlideAddResponse)

Color = _reflection.GeneratedProtocolMessageType('Color', (_message.Message,), {
  'DESCRIPTOR' : _COLOR,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:mpf.Color)
  })
_sym_db.RegisterMessage(Color)

WidgetAddRequest = _reflection.GeneratedProtocolMessageType('WidgetAddRequest', (_message.Message,), {

  'WidgetText' : _reflection.GeneratedProtocolMessageType('WidgetText', (_message.Message,), {
    'DESCRIPTOR' : _WIDGETADDREQUEST_WIDGETTEXT,
    '__module__' : 'server_pb2'
    # @@protoc_insertion_point(class_scope:mpf.WidgetAddRequest.WidgetText)
    })
  ,

  'WidgetRectangle' : _reflection.GeneratedProtocolMessageType('WidgetRectangle', (_message.Message,), {
    'DESCRIPTOR' : _WIDGETADDREQUEST_WIDGETRECTANGLE,
    '__module__' : 'server_pb2'
    # @@protoc_insertion_point(class_scope:mpf.WidgetAddRequest.WidgetRectangle)
    })
  ,

  'WidgetImage' : _reflection.GeneratedProtocolMessageType('WidgetImage', (_message.Message,), {
    'DESCRIPTOR' : _WIDGETADDREQUEST_WIDGETIMAGE,
    '__module__' : 'server_pb2'
    # @@protoc_insertion_point(class_scope:mpf.WidgetAddRequest.WidgetImage)
    })
  ,
  'DESCRIPTOR' : _WIDGETADDREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:mpf.WidgetAddRequest)
  })
_sym_db.RegisterMessage(WidgetAddRequest)
_sym_db.RegisterMessage(WidgetAddRequest.WidgetText)
_sym_db.RegisterMessage(WidgetAddRequest.WidgetRectangle)
_sym_db.RegisterMessage(WidgetAddRequest.WidgetImage)

WidgetAddResponse = _reflection.GeneratedProtocolMessageType('WidgetAddResponse', (_message.Message,), {
  'DESCRIPTOR' : _WIDGETADDRESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:mpf.WidgetAddResponse)
  })
_sym_db.RegisterMessage(WidgetAddResponse)

ShowSlideRequest = _reflection.GeneratedProtocolMessageType('ShowSlideRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHOWSLIDEREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:mpf.ShowSlideRequest)
  })
_sym_db.RegisterMessage(ShowSlideRequest)

ShowSlideResponse = _reflection.GeneratedProtocolMessageType('ShowSlideResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHOWSLIDERESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:mpf.ShowSlideResponse)
  })
_sym_db.RegisterMessage(ShowSlideResponse)



_MEDIACONTROLLER = _descriptor.ServiceDescriptor(
  name='MediaController',
  full_name='mpf.MediaController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=655,
  serialized_end=857,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddSlide',
    full_name='mpf.MediaController.AddSlide',
    index=0,
    containing_service=None,
    input_type=_SLIDEADDREQUEST,
    output_type=_SLIDEADDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddWidgetsToSlide',
    full_name='mpf.MediaController.AddWidgetsToSlide',
    index=1,
    containing_service=None,
    input_type=_WIDGETADDREQUEST,
    output_type=_WIDGETADDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ShowSlide',
    full_name='mpf.MediaController.ShowSlide',
    index=2,
    containing_service=None,
    input_type=_SHOWSLIDEREQUEST,
    output_type=_SHOWSLIDERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEDIACONTROLLER)

DESCRIPTOR.services_by_name['MediaController'] = _MEDIACONTROLLER

# @@protoc_insertion_point(module_scope)
