# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='mpf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cserver.proto\x12\x03mpf\"\x11\n\x0fSlideAddRequest\"$\n\x10SlideAddResponse\x12\x10\n\x08slide_id\x18\x01 \x01(\r\"2\n\x10WidgetAddRequest\x12\x10\n\x08slide_id\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x13\n\x11WidgetAddResponse\"$\n\x10ShowSlideRequest\x12\x10\n\x08slide_id\x18\x01 \x01(\r\"\x13\n\x11ShowSlideResponse2\xca\x01\n\x0fMediaController\x12\x37\n\x08\x41\x64\x64Slide\x12\x14.mpf.SlideAddRequest\x1a\x15.mpf.SlideAddResponse\x12\x42\n\x11\x41\x64\x64WidgetsToSlide\x12\x15.mpf.WidgetAddRequest\x1a\x16.mpf.WidgetAddResponse\x12:\n\tShowSlide\x12\x15.mpf.ShowSlideRequest\x1a\x16.mpf.ShowSlideResponseb\x06proto3'
)




_SLIDEADDREQUEST = _descriptor.Descriptor(
  name='SlideAddRequest',
  full_name='mpf.SlideAddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=38,
)


_SLIDEADDRESPONSE = _descriptor.Descriptor(
  name='SlideAddResponse',
  full_name='mpf.SlideAddResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='slide_id', full_name='mpf.SlideAddResponse.slide_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=76,
)


_WIDGETADDREQUEST = _descriptor.Descriptor(
  name='WidgetAddRequest',
  full_name='mpf.WidgetAddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='slide_id', full_name='mpf.WidgetAddRequest.slide_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='mpf.WidgetAddRequest.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=128,
)


_WIDGETADDRESPONSE = _descriptor.Descriptor(
  name='WidgetAddResponse',
  full_name='mpf.WidgetAddResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=149,
)


_SHOWSLIDEREQUEST = _descriptor.Descriptor(
  name='ShowSlideRequest',
  full_name='mpf.ShowSlideRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='slide_id', full_name='mpf.ShowSlideRequest.slide_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=187,
)


_SHOWSLIDERESPONSE = _descriptor.Descriptor(
  name='ShowSlideResponse',
  full_name='mpf.ShowSlideResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=208,
)

DESCRIPTOR.message_types_by_name['SlideAddRequest'] = _SLIDEADDREQUEST
DESCRIPTOR.message_types_by_name['SlideAddResponse'] = _SLIDEADDRESPONSE
DESCRIPTOR.message_types_by_name['WidgetAddRequest'] = _WIDGETADDREQUEST
DESCRIPTOR.message_types_by_name['WidgetAddResponse'] = _WIDGETADDRESPONSE
DESCRIPTOR.message_types_by_name['ShowSlideRequest'] = _SHOWSLIDEREQUEST
DESCRIPTOR.message_types_by_name['ShowSlideResponse'] = _SHOWSLIDERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SlideAddRequest = _reflection.GeneratedProtocolMessageType('SlideAddRequest', (_message.Message,), {
  'DESCRIPTOR' : _SLIDEADDREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:mpf.SlideAddRequest)
  })
_sym_db.RegisterMessage(SlideAddRequest)

SlideAddResponse = _reflection.GeneratedProtocolMessageType('SlideAddResponse', (_message.Message,), {
  'DESCRIPTOR' : _SLIDEADDRESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:mpf.SlideAddResponse)
  })
_sym_db.RegisterMessage(SlideAddResponse)

WidgetAddRequest = _reflection.GeneratedProtocolMessageType('WidgetAddRequest', (_message.Message,), {
  'DESCRIPTOR' : _WIDGETADDREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:mpf.WidgetAddRequest)
  })
_sym_db.RegisterMessage(WidgetAddRequest)

WidgetAddResponse = _reflection.GeneratedProtocolMessageType('WidgetAddResponse', (_message.Message,), {
  'DESCRIPTOR' : _WIDGETADDRESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:mpf.WidgetAddResponse)
  })
_sym_db.RegisterMessage(WidgetAddResponse)

ShowSlideRequest = _reflection.GeneratedProtocolMessageType('ShowSlideRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHOWSLIDEREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:mpf.ShowSlideRequest)
  })
_sym_db.RegisterMessage(ShowSlideRequest)

ShowSlideResponse = _reflection.GeneratedProtocolMessageType('ShowSlideResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHOWSLIDERESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:mpf.ShowSlideResponse)
  })
_sym_db.RegisterMessage(ShowSlideResponse)



_MEDIACONTROLLER = _descriptor.ServiceDescriptor(
  name='MediaController',
  full_name='mpf.MediaController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=211,
  serialized_end=413,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddSlide',
    full_name='mpf.MediaController.AddSlide',
    index=0,
    containing_service=None,
    input_type=_SLIDEADDREQUEST,
    output_type=_SLIDEADDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddWidgetsToSlide',
    full_name='mpf.MediaController.AddWidgetsToSlide',
    index=1,
    containing_service=None,
    input_type=_WIDGETADDREQUEST,
    output_type=_WIDGETADDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ShowSlide',
    full_name='mpf.MediaController.ShowSlide',
    index=2,
    containing_service=None,
    input_type=_SHOWSLIDEREQUEST,
    output_type=_SHOWSLIDERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEDIACONTROLLER)

DESCRIPTOR.services_by_name['MediaController'] = _MEDIACONTROLLER

# @@protoc_insertion_point(module_scope)
